# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2.0'

# Rails framework
gem 'rails', '~> 7.0'

# Database
gem 'sqlite3', '~> 1.4'

# EzCondition (local path)
gem 'ez_condition', path: '../..'

# Web server
gem 'puma', '~> 6.0'

# Assets
gem 'sprockets-rails'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'

# JSON
gem 'jbuilder'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'debug'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'database_cleaner-active_record'
end
